---
# Source: rancher/templates/serviceAccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: release-name-rancher
  labels:
    app: release-name-rancher
    chart: rancher-2019.1.1
    heritage: Tiller
    release: release-name